import turtle
myturtle = turtle.Turtle()
myscreen = turtle.Screen()
myscreen.bgcolor("black")
myturtle.color("yellow")

myturtle.pensize(5)
myturtle.speed(7)

myturtle.penup()
myturtle.backward(100)
myturtle.pendown()
myturtle.right(60)
myturtle.forward(100)
myturtle.left(120)
myturtle.forward(100)
myturtle.right(60)
myturtle.penup()
myturtle.forward(30)
myturtle.right(120)
myturtle.pendown()
myturtle.forward(100)
myturtle.backward(50)
myturtle.left(120)
myturtle.forward(50)
myturtle.right(60)
myturtle.forward(50)
myturtle.backward(100)
myturtle.left(60)
myturtle.penup()
myturtle.forward(90)
myturtle.left(45)
myturtle.pendown()
myturtle.backward(50)
myturtle.right(90)
myturtle.forward(50)
myturtle.right(90)
myturtle.forward(50)
myturtle.penup()
myturtle.backward(25)
myturtle.left(135)
myturtle.forward(50)
myturtle.left(90)
myturtle.pendown()
myturtle.forward(90)
myturtle.penup()
myturtle.backward(90)
myturtle.right(90)
myturtle.pendown()
myturtle.forward(50)
myturtle.left(90)
myturtle.forward(90)
myturtle.left(180)

myturtle.penup()
myturtle.forward(110)
myturtle.right(90)
myturtle.forward(270)
myturtle.right(180)
myturtle.pendown()
myturtle.forward(280)

